# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpcgi._proto.grpcgi.v1 import http_pb2 as grpcgi_dot_v1_dot_http__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpcgi/v1/http_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HttpBridgeStub(object):
    """HTTP bridge service. Envoy's ext_proc filter calls Process() for each
    HTTP request. grpcgi reconstructs the full ASGI http scope from the
    stream of ProcessingRequest messages and streams ProcessingResponse
    messages back as the ASGI app produces response events.

    NOTE: This is a simplified prototype proto. Production should implement
    the full Envoy ext_proc protocol:
    envoy.service.ext_proc.v3.ExternalProcessor
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handle = channel.unary_unary(
                '/grpcgi.v1.HttpBridge/Handle',
                request_serializer=grpcgi_dot_v1_dot_http__pb2.HttpRequest.SerializeToString,
                response_deserializer=grpcgi_dot_v1_dot_http__pb2.HttpResponse.FromString,
                _registered_method=True)
        self.Process = channel.stream_stream(
                '/grpcgi.v1.HttpBridge/Process',
                request_serializer=grpcgi_dot_v1_dot_http__pb2.ProcessingRequest.SerializeToString,
                response_deserializer=grpcgi_dot_v1_dot_http__pb2.ProcessingResponse.FromString,
                _registered_method=True)


class HttpBridgeServicer(object):
    """HTTP bridge service. Envoy's ext_proc filter calls Process() for each
    HTTP request. grpcgi reconstructs the full ASGI http scope from the
    stream of ProcessingRequest messages and streams ProcessingResponse
    messages back as the ASGI app produces response events.

    NOTE: This is a simplified prototype proto. Production should implement
    the full Envoy ext_proc protocol:
    envoy.service.ext_proc.v3.ExternalProcessor
    """

    def Handle(self, request, context):
        """Unary RPC used by the Envoy WASM filter via dispatch_grpc_call.
        Full request (headers + body) in, full response (status + headers + body) out.
        Suitable for typical HTTP request/response; body is buffered on both sides.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request_iterator, context):
        """Bidi-streaming RPC for chunked/streaming responses (SSE, large files).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HttpBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handle': grpc.unary_unary_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=grpcgi_dot_v1_dot_http__pb2.HttpRequest.FromString,
                    response_serializer=grpcgi_dot_v1_dot_http__pb2.HttpResponse.SerializeToString,
            ),
            'Process': grpc.stream_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=grpcgi_dot_v1_dot_http__pb2.ProcessingRequest.FromString,
                    response_serializer=grpcgi_dot_v1_dot_http__pb2.ProcessingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcgi.v1.HttpBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpcgi.v1.HttpBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HttpBridge(object):
    """HTTP bridge service. Envoy's ext_proc filter calls Process() for each
    HTTP request. grpcgi reconstructs the full ASGI http scope from the
    stream of ProcessingRequest messages and streams ProcessingResponse
    messages back as the ASGI app produces response events.

    NOTE: This is a simplified prototype proto. Production should implement
    the full Envoy ext_proc protocol:
    envoy.service.ext_proc.v3.ExternalProcessor
    """

    @staticmethod
    def Handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcgi.v1.HttpBridge/Handle',
            grpcgi_dot_v1_dot_http__pb2.HttpRequest.SerializeToString,
            grpcgi_dot_v1_dot_http__pb2.HttpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpcgi.v1.HttpBridge/Process',
            grpcgi_dot_v1_dot_http__pb2.ProcessingRequest.SerializeToString,
            grpcgi_dot_v1_dot_http__pb2.ProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
