# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpcgi._proto.grpcgi.v1 import websocket_pb2 as grpcgi_dot_v1_dot_websocket__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpcgi/v1/websocket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebSocketBridgeStub(object):
    """WebSocket bridge service. The Envoy WASM/native filter establishes one
    bidi-streaming Connect call per WebSocket connection. HTTP upgrade
    metadata (path, headers) is passed as gRPC initial metadata so grpcgi
    can reconstruct the ASGI websocket scope without widening this message.

    Control frames (ping/pong) are handled entirely by the Envoy filter and
    never forwarded here. gRPC keepalive is configured independently between
    Envoy and grpcgi. Close (opcode 0x08) is signalled by closing the stream.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/grpcgi.v1.WebSocketBridge/Connect',
                request_serializer=grpcgi_dot_v1_dot_websocket__pb2.Frame.SerializeToString,
                response_deserializer=grpcgi_dot_v1_dot_websocket__pb2.Frame.FromString,
                _registered_method=True)
        self.Session = channel.stream_stream(
                '/grpcgi.v1.WebSocketBridge/Session',
                request_serializer=grpcgi_dot_v1_dot_websocket__pb2.WebSocketEvent.SerializeToString,
                response_deserializer=grpcgi_dot_v1_dot_websocket__pb2.WebSocketEvent.FromString,
                _registered_method=True)


class WebSocketBridgeServicer(object):
    """WebSocket bridge service. The Envoy WASM/native filter establishes one
    bidi-streaming Connect call per WebSocket connection. HTTP upgrade
    metadata (path, headers) is passed as gRPC initial metadata so grpcgi
    can reconstruct the ASGI websocket scope without widening this message.

    Control frames (ping/pong) are handled entirely by the Envoy filter and
    never forwarded here. gRPC keepalive is configured independently between
    Envoy and grpcgi. Close (opcode 0x08) is signalled by closing the stream.
    """

    def Connect(self, request_iterator, context):
        """Legacy data-only RPC. Handshake state is carried in gRPC metadata and
        stream closure loses the WebSocket close code. Retained for deployed
        prototype clients; new implementations use Session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Session(self, request_iterator, context):
        """Complete WebSocket lifecycle. The first client event is open; the first
        server event is accept or reject; data follows only after accept; either
        peer may finish with close.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebSocketBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=grpcgi_dot_v1_dot_websocket__pb2.Frame.FromString,
                    response_serializer=grpcgi_dot_v1_dot_websocket__pb2.Frame.SerializeToString,
            ),
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=grpcgi_dot_v1_dot_websocket__pb2.WebSocketEvent.FromString,
                    response_serializer=grpcgi_dot_v1_dot_websocket__pb2.WebSocketEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcgi.v1.WebSocketBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpcgi.v1.WebSocketBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebSocketBridge(object):
    """WebSocket bridge service. The Envoy WASM/native filter establishes one
    bidi-streaming Connect call per WebSocket connection. HTTP upgrade
    metadata (path, headers) is passed as gRPC initial metadata so grpcgi
    can reconstruct the ASGI websocket scope without widening this message.

    Control frames (ping/pong) are handled entirely by the Envoy filter and
    never forwarded here. gRPC keepalive is configured independently between
    Envoy and grpcgi. Close (opcode 0x08) is signalled by closing the stream.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpcgi.v1.WebSocketBridge/Connect',
            grpcgi_dot_v1_dot_websocket__pb2.Frame.SerializeToString,
            grpcgi_dot_v1_dot_websocket__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpcgi.v1.WebSocketBridge/Session',
            grpcgi_dot_v1_dot_websocket__pb2.WebSocketEvent.SerializeToString,
            grpcgi_dot_v1_dot_websocket__pb2.WebSocketEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
