# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcgi/v1/websocket.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpcgi/v1/websocket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpcgi._proto.grpcgi.v1 import http_pb2 as grpcgi_dot_v1_dot_http__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpcgi/v1/websocket.proto\x12\tgrpcgi.v1\x1a\x14grpcgi/v1/http.proto\"(\n\x05\x46rame\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0e\n\x06\x62inary\x18\x02 \x01(\x08\"\xf5\x01\n\x0eWebSocketEvent\x12(\n\x04open\x18\x01 \x01(\x0b\x32\x18.grpcgi.v1.WebSocketOpenH\x00\x12,\n\x06\x61\x63\x63\x65pt\x18\x02 \x01(\x0b\x32\x1a.grpcgi.v1.WebSocketAcceptH\x00\x12,\n\x06reject\x18\x03 \x01(\x0b\x32\x1a.grpcgi.v1.WebSocketRejectH\x00\x12(\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x18.grpcgi.v1.WebSocketDataH\x00\x12*\n\x05\x63lose\x18\x05 \x01(\x0b\x32\x19.grpcgi.v1.WebSocketCloseH\x00\x42\x07\n\x05\x65vent\"\xba\x01\n\rWebSocketOpen\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06scheme\x18\x02 \x01(\t\x12\x11\n\tauthority\x18\x03 \x01(\t\x12\"\n\x07headers\x18\x04 \x03(\x0b\x32\x11.grpcgi.v1.Header\x12\x14\n\x0csubprotocols\x18\x05 \x03(\t\x12\x16\n\x0eremote_address\x18\x06 \x01(\t\x12\x13\n\x0bremote_port\x18\x07 \x01(\r\x12\x11\n\troot_path\x18\x08 \x01(\t\"J\n\x0fWebSocketAccept\x12\x13\n\x0bsubprotocol\x18\x01 \x01(\t\x12\"\n\x07headers\x18\x02 \x03(\x0b\x32\x11.grpcgi.v1.Header\"S\n\x0fWebSocketReject\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\"\n\x07headers\x18\x02 \x03(\x0b\x32\x11.grpcgi.v1.Header\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"0\n\rWebSocketData\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0e\n\x06\x62inary\x18\x02 \x01(\x08\".\n\x0eWebSocketClose\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x89\x01\n\x0fWebSocketBridge\x12\x31\n\x07\x43onnect\x12\x10.grpcgi.v1.Frame\x1a\x10.grpcgi.v1.Frame(\x01\x30\x01\x12\x43\n\x07Session\x12\x19.grpcgi.v1.WebSocketEvent\x1a\x19.grpcgi.v1.WebSocketEvent(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcgi.v1.websocket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=62
  _globals['_FRAME']._serialized_end=102
  _globals['_WEBSOCKETEVENT']._serialized_start=105
  _globals['_WEBSOCKETEVENT']._serialized_end=350
  _globals['_WEBSOCKETOPEN']._serialized_start=353
  _globals['_WEBSOCKETOPEN']._serialized_end=539
  _globals['_WEBSOCKETACCEPT']._serialized_start=541
  _globals['_WEBSOCKETACCEPT']._serialized_end=615
  _globals['_WEBSOCKETREJECT']._serialized_start=617
  _globals['_WEBSOCKETREJECT']._serialized_end=700
  _globals['_WEBSOCKETDATA']._serialized_start=702
  _globals['_WEBSOCKETDATA']._serialized_end=750
  _globals['_WEBSOCKETCLOSE']._serialized_start=752
  _globals['_WEBSOCKETCLOSE']._serialized_end=798
  _globals['_WEBSOCKETBRIDGE']._serialized_start=801
  _globals['_WEBSOCKETBRIDGE']._serialized_end=938
# @@protoc_insertion_point(module_scope)
