#!/usr/bin/env bash
# Regenerate docs/spec/vectors/vectors.md from the .txtpb inputs next to it.
# Each input names its message type on the first line: "# type: <fqn>".
# Requires protoc on PATH and the well-known types under /opt/homebrew/include
# or /usr/local/include.
set -euo pipefail
cd "$(dirname "$0")/../../.."
INC=""
for d in /opt/homebrew/include /usr/local/include /usr/include; do
  [ -d "$d/google/protobuf" ] && INC="-I $d" && break
done
OUT=docs/spec/vectors/vectors.md
{
  echo "# grpcgi v1alpha1 golden vectors"
  echo
  echo "Generated by \`docs/spec/tools/vectors.sh\` from the \`.txtpb\` files in this"
  echo "directory using \`protoc --encode\`. Each vector is one event message as it"
  echo "appears inside a gRPC message frame or a local-binding DATA frame, without"
  echo "any length prefix. A conforming encoder MUST produce these exact bytes for"
  echo "these inputs; a conforming decoder MUST accept them."
  echo
  for f in docs/spec/vectors/*.txtpb; do
    name=$(basename "$f" .txtpb)
    type=$(sed -n '1s/^# type: //p' "$f")
    hex=$(protoc -I proto $INC --encode="$type" proto/grpcgi/v1alpha1/exchange.proto < "$f" | xxd -p | tr -d '\n')
    len=$(( ${#hex} / 2 ))
    echo "## $name"
    echo
    echo "Type: \`$type\` ($len bytes)"
    echo
    echo '```textproto'
    sed '1d' "$f"
    echo '```'
    echo
    echo '```'
    echo "$hex" | fold -w 64
    echo '```'
    echo
  done
} > "$OUT"
echo "wrote $OUT"
